### ISSUE TITLE
All BattleTags in database.

### ISSUE THREAD

**Issue by Wobbley** [Wobbley/HotS-Willie-Module#1]
Create a command that displays all BattleTags in the database and the corresponding IRC username, perhaps as PM.

**Comment by Wobbley** [comment]
How can this be done without avoiding a flood?

**Comment by chadrien** [comment]
What would be the goal of such command?

**Comment by KDKNFT** [comment]
to add everybody from irc in your friendslist if you have nobody to play with, at least you know these people are cool and/or trying harder

**Comment by chadrien** [comment]
I see.

I'll take a look at python packages to manipulate gists then. It could be as simple as dumping all the tags in a gist and giving the gist url to the user asking for the full list

Edit: this lib could be a good start https://github.com/softvar/simplegist

**Comment by chadrien** [comment]
Maybe the generated gist should contain multiple files: one per region. Because people should be mainly interested in a list containing only bnet accounts from their region I guess.

@Wobbley, @KenziDK: thoughts on that?

**Comment by Wobbley** [comment]
Gist is perhaps a better idea yes, I was thinking of using github.io.

I am a bit worried if this is an actual wanted feature though, or just something kenzi has suggested cause he is mad. Not to mention we are putting everyones battle.net accounts out on the internet.

**Comment by chadrien** [comment]
The gist can be private (not linked anywhere, you have to know the URL to access it). Plus people already put their bnet account on the internet as their gave them to the bot (which is on the internet :stuck_out_tongue:)

I agree however that this might not be an actual desired feature. How could we figure this out? A poll?

**Comment by Wobbley** [comment]
I honestly don't know, it's a cool feature to play with, but do we have
anything more important?

**Comment by Wobbley** [comment]
The thing with polls is that people usually answers "yes that is a feature
I want or will use" but they do it because it sounds cool, not because they
need it and will use it.

**Comment by KDKNFT** [comment]
I'll ask around and see what people think

**Comment by Centopus** [comment]
Add a setting for users, to allow them a choice (public/irc only).  Where public means their tag+irc name is visible in both ways, and "irc only" would make it not show up in the list.

**Comment by moopie** [comment]
Couple of problems with this feature:
1. Flood - poor bot will be kicked around like a turkey
2. No real use - the beauty of current implementation is that you at least interact with the guy before you get his battle.net info
3. Who all these weird people that keep messaging me? - Come on, do we really need some people who idle on the channel to suddenly be able to add everyone from that list? I don't. I don't even like people

Although, if it is a feature that people might really want for some reason, may I suggest adding a web interface to the bot thus allowing to just share the link to the full battlenet tag list instead of spamming the irc server.

Or, as @chadrien said, adding an ability to paste the full list to some pastebin-like website. that can work too.

**Comment by Wobbley** [comment]
@moopie We never intended the bot to spam someone with the entire list, but rather export it to somewhere it expires. Like pastebin or gist.

I am still unsure about this feature myself, I added myself to the Ryse public forums "lfg" thread, and have gotten tons of new friends. Sadly I have only played with like 3/10, because the other are american or play at different times.

The thing is you can import 10 players, and all of them are a miss, as @moopie states, it is better to interact with them first.

**Comment by KDKNFT** [comment]
Fair point mentioned by @moopie
"No real use - the beauty of current implementation is that you at least interact with the guy before you get his battle.net info"

I rest my case.

**Comment by chadrien** [comment]
Should we all agree this feature is not necessary and close this issue?

**Comment by Wobbley** [comment]
Closed, it can be revived in the future if deemed neccessary, or someone is really bored
