### ISSUE TITLE
pull the !rotation info from somewhere else

### ISSUE THREAD

**Issue by KDKNFT** [Wobbley/HotS-Willie-Module#15]
as Heroesfire appeared to be extremely slow ( 2 days to update the rotation) maybe it's a better idea to pull the info from http://heroesofthestorm.github.io/free-hero-rotation ? iirc it's updated much faster than heroesfire is
don't know if it's possible, me very dump

**Comment by chadrien** [comment]
:+1: 

It's around https://github.com/Wobbley/HotS-Willie-Module/blob/master/hots.py#L181

Should be simple to change
