### ISSUE TITLE
!rating is not working properly

### ISSUE THREAD

**Issue by Wobbley** [Wobbley/HotS-Willie-Module#20]
Hotslogs has changed, if it only finds one player with the given name it will immediately show that player, hence there will be no table to retrieve the MMR from.

**Comment by Wobbley** [comment]
Ravilan: !rating Ravilan
Hotsbot: AttributeError: 'NoneType' object has no attribute 'previous_sibling' (file "/home/ubuntu/.willie/modules/hots.py", line 96, in hotslogs_rating)

**Comment by KDKNFT** [comment]
![](https://i.imgur.com/f8WKHGN.jpg)
