### ISSUE TITLE
Add a command like this ??addbt <user> to highlight the user with an explanation on how to add his infos

### ISSUE THREAD

**Issue by KDKNFT** [Wobbley/HotS-Willie-Module#3]
Would do something like this : 
hotsbot: Wobbley, you can add your battle.net infos like this !addbt /tag/ /region/

But automatically!

you're welcome

**Comment by chadrien** [comment]
A quick win could be to create a `!help` command displaying the example of the given command.

**Comment by KDKNFT** [comment]
Sounds about right
