### ISSUE TITLE
!rotation seems bugged

### ISSUE THREAD

**Issue by chadrien** [Wobbley/HotS-Willie-Module#30]
![screenshot 2015-01-21 11 33 37](https://cloud.githubusercontent.com/assets/1788218/5834784/68ba95ae-a161-11e4-897d-994096213013.png)

Maybe we should add a fallback: if the list is empty, print the URL instead

**Comment by KDKNFT** [comment]
https://github.com/heroesofthestorm/heroesofthestorm.github.io/pull/2#issuecomment-70778224

**Comment by chadrien** [comment]
@KenziDK: good!

I'll work on the fallback anyway. At least the feature will be "external service problem" proof

**Comment by KDKNFT** [comment]
yay \o/

**Comment by Wobbley** [comment]
So is this issue closed or not?

**Comment by KDKNFT** [comment]
No, Hadrien didn't do his part yet.
On 21/01/2015 15:43, Dean wrote:

> So is this issue closed or not?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Wobbley/HotS-Willie-Module/issues/30#issuecomment-70848534.

---

L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by KDKNFT** [comment]
and btw @Wobbley you gotta fix the original code though, or @chadrien :o)
