### ISSUE TITLE
limit the result of !rotation to 7

### ISSUE THREAD

**Issue by KDKNFT** [Wobbley/HotS-Willie-Module#36]
sometimes the guy of http://heroesofthestorm.github.io/free-hero-rotation leaves the heroes of the previous week in there for a few hours/days
maybe you can adapt the bot so that it only prints 7 names, instead of all the ones on the page?

07:36:56 <blake> !rotation
07:36:56 <+Hotsbot> Free rotation: Arthas, E.T.C, Kerrigan, Li Li, Nazeebo, Tychus, Uther, Falstad, Malfurion, Sonya, Stitches, Valla, Sergeant Hammer, Brightwing

**Comment by chadrien** [comment]
For this example, the good rotation was "Arthas, E.T.C, Kerrigan, Li Li, Nazeebo, Tychus, Uther" right?

**Comment by KDKNFT** [comment]
yeh, it's usually always the first 7 that are the right ones.
so you could limit the bot to just pull 7 names; it should be the correct ones.

**Comment by chadrien** [comment]
Fixed in e54b9492a9b435460d3ec9f56fc030d1fe4c4191
