### ISSUE TITLE
Make !ts call the same command as !ts3

### ISSUE THREAD

**Issue by Wobbley** [Wobbley/HotS-Willie-Module#39]
It's an easy fix, I will just do it directly in github if possible

**Comment by Wobbley** [comment]
Fixed in: e7b9f8dffc4aa10de54b8eff9c85e5ad45f1876d

**Comment by chadrien** [comment]
@Wobbley: can we close the issue then?

**Comment by Wobbley** [comment]
@chadrien  Yes :+1:
