### ISSUE TITLE
Add unit testing

### ISSUE THREAD

**Issue by chadrien** [Wobbley/HotS-Willie-Module#43]
See https://github.com/embolalia/willie/wiki/Examples-and-units-tests

**Comment by Wobbley** [comment]
This has been on my todo list for ages, willie has some testing, and it is simple for static methods. A large amount of our content is dynamic though. I really have to figure out how to "mock" data and responses in python for those methods.

**Comment by Wobbley** [comment]
Nobody has worked on this for a while, closing it all down :)
