### ISSUE TITLE
the errors with accents éàä etc

### ISSUE THREAD

**Issue by KDKNFT** [Wobbley/HotS-Willie-Module#47]
08:02:06 <nasir> !rating kenzi
08:02:08 <+Hotsbot> AttributeError: 'NoneType' object has no attribute 'previous_sibling' (file "/home/willie/.willie/modules/hots.py", line 93, in hotslogs_rating)

happens because of the Kénzi guy, is that easily fixable?

**Comment by Wobbley** [comment]
Yes and no. It is doable but my inital solution would involve a method with
large amounts of .replace. not sure if there is a more elegant way
