### ISSUE TITLE
Hide players without rating from the list?

### ISSUE THREAD

**Issue by chadrien** [Wobbley/HotS-Willie-Module#48]
> HotSBotRavilan: Kenzi [EU] -   [2185]
> HotSBotRavilan: Kenzi [US] -   [ ]
> HotSBotRavilan: Kénzi [EU] -   [ ]
> HotSBotRavilan: Kenzi [EU] -   [ ]
> HotSBotRavilan: KENZI [KR] -   [ ]

In this case, only display the first one, ignoring the rest of it.

Also, league seems to be broken, maybe remove it from the list?

**Comment by Wobbley** [comment]
Yes, yes we should

On Fri, Feb 6, 2015 at 2:45 PM, Hadrien Collongues <notifications@github.com

**Comment by KDKNFT** [comment]
okay but there should be an alternative if there's nothing at all in the brackets; like a link to the search page?
