### ISSUE TITLE
Brand new bot?

### ISSUE THREAD

**Issue by chadrien** [Wobbley/HotS-Willie-Module#49]
So… as you know I've started to play with IRC bots in ruby, and I've almost finished a Hotsbot clone in ruby, but this one is: tested, has (almost) complete docs, is imo more maintainable (we can split code into files, tests are made easy) and is based on a bot framework having a good documentation (I'm looking at you willie)!

So the question is: would you guys be ok with kicking out the bot based on willie and replace it with this one?

Sources can be found here: https://github.com/chadrien/hots-irc-bot

**Comment by Wobbley** [comment]
I am fine with replacing the python bot. It was more of a fun go at python for me during christmas, and I have no problems with replacing it. Especially since you are doing more work on it latley

**Comment by chadrien** [comment]
New bot is live :smile:
